services:
  - type: web
    name: agrovers-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: "pip install -r backend/requirements.txt && cd backend && python preprocess_kb.py"
    startCommand: "cd backend && gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
      - key: OLLAMA_MODEL_NAME
        value: gemma2:9b
